"""empty message

Revision ID: 25dc4bc82af9
Revises: 619dbedbc3cb
Create Date: 2024-04-20 21:34:57.009611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25dc4bc82af9'
down_revision = '619dbedbc3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jitsi_room_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('jitsi_room_id')

    # ### end Alembic commands ###
