"""empty message

Revision ID: 619dbedbc3cb
Revises: ac8c48cd9778
Create Date: 2024-04-19 13:45:25.853576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619dbedbc3cb'
down_revision = 'ac8c48cd9778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_submissions_answer_id_answers')),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_submissions_exam_id_exams')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_submissions_question_id_questions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_submissions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('biography')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biography', sa.VARCHAR(), nullable=True))

    op.drop_table('submissions')
    # ### end Alembic commands ###
