"""empty message

Revision ID: 6972fc2dc21a
Revises: 25dc4bc82af9
Create Date: 2024-04-24 17:47:19.781216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6972fc2dc21a'
down_revision = '25dc4bc82af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_photo_exam_id_exams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_photo_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###
